const K='fraisProxiProducts';let data=JSON.parse(localStorage.getItem(K)||'[]'),filter='all';
const $=x=>document.getElementById(x),iso=d=>{let x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
const add=(d,n)=>{let x=new Date(d);x.setDate(x.getDate()+n);return x},fmt=d=>new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(d));
function monday(d=new Date()){let x=new Date(d),n=(x.getDay()+6)%7;x.setDate(x.getDate()-n);x.setHours(0,0,0,0);return x}
function status(p){let t=iso(new Date()),tom=iso(add(new Date(),1)),e=p.dlc;if(e<=t)return['À retirer','danger'];if(e===tom)return['Demain','warn'];let end=add(monday(),6);return new Date(e)<=end?['Cette semaine','ok']:['À venir','ok']}
function save(){localStorage.setItem(K,JSON.stringify(data))}
function show(id){['home','add','products','stats'].forEach(x=>$(x).hidden=x!==id);if(id==='stats')renderStats()}
function match(p){let s=status(p)[0];if(filter==='today')return s==='À retirer';if(filter==='tomorrow')return s==='Demain';if(filter==='week')return ['À retirer','Demain','Cette semaine'].includes(s);return true}
function render(){let now=new Date();$('today').textContent=new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long'}).format(now);$('week').textContent=`Semaine du ${fmt(monday())} au ${fmt(add(monday(),6))}`;
let active=data.filter(p=>!p.done);$('cToday').textContent=active.filter(p=>status(p)[0]==='À retirer').reduce((a,p)=>a+p.qty,0);$('cTomorrow').textContent=active.filter(p=>status(p)[0]==='Demain').reduce((a,p)=>a+p.qty,0);$('cWeek').textContent=active.filter(p=>['À retirer','Demain','Cette semaine'].includes(status(p)[0])).reduce((a,p)=>a+p.qty,0);
$('days').innerHTML=[0,1,2,3,4].map(i=>{let d=add(monday(),i),n=active.filter(p=>p.dlc===iso(d)).reduce((a,p)=>a+p.qty,0);return `<div class=day><b>${['Lun','Mar','Mer','Jeu','Ven'][i]}</b><span>${d.getDate()}</span><strong>${n}</strong></div>`}).join('');renderList()}
function renderList(){let term=($('search')?.value||'').toLowerCase();let arr=data.filter(p=>match(p)&&p.name.toLowerCase().includes(term)).sort((a,b)=>a.dlc.localeCompare(b.dlc));$('list').innerHTML=arr.length?arr.map(p=>{let s=status(p);return `<div class=item><div class=info><b>${p.name} ×${p.qty}</b><small>${p.rayon} · DLC ${fmt(p.dlc)}${p.barcode?' · '+p.barcode:''}</small><span class="badge ${s[1]}">${p.done?'Retiré':s[0]}</span></div><button class=done onclick="done('${p.id}')">✓</button><button class=del onclick="del('${p.id}')">×</button></div>`}).join(''):'<p>Aucun produit.</p>'}
function filterList(f){filter=f;show('products');renderList()}
function done(id){let p=data.find(x=>x.id===id);p.done=!p.done;p.doneAt=p.done?new Date().toISOString():null;save();render()}
function del(id){data=data.filter(x=>x.id!==id);save();render()}
function renderStats(){let w=data.filter(p=>new Date(p.dlc)>=monday()&&new Date(p.dlc)<=add(monday(),7)),done=w.filter(p=>p.done).reduce((a,p)=>a+p.qty,0),pending=w.filter(p=>!p.done).reduce((a,p)=>a+p.qty,0);let by={};w.forEach(p=>by[p.rayon]=(by[p.rayon]||0)+p.qty);$('statsBox').innerHTML=`<div class="card green"><b>${done}</b><span>produits retirés</span></div><div class="card orange"><b>${pending}</b><span>en attente</span></div><h3>Répartition par rayon</h3>`+Object.entries(by).map(([k,v])=>`<div class=item><div class=info><b>${k}</b></div><strong>${v}</strong></div>`).join('')}
$('form').onsubmit=e=>{e.preventDefault();data.push({id:Date.now().toString(36),name:$('name').value.trim(),barcode:$('barcode').value.trim(),qty:+$('qty').value,dlc:$('dlc').value,rayon:$('rayon').value,notes:$('notes').value.trim(),done:false});save();e.target.reset();$('qty').value=1;render();filterList('all')};render();