-- Frais Proxi V5.3 — rôles Administrateur / Employé + rayons synchronisés
-- À exécuter UNE FOIS dans Supabase > SQL Editor, sans sélectionner seulement une partie.

alter table public.acces_magasin add column if not exists role text not null default 'employe';
alter table public.acces_magasin add column if not exists nom_affichage text;
alter table public.acces_magasin add column if not exists actif boolean not null default true;
alter table public.acces_magasin add column if not exists updated_at timestamptz default now();

-- Normalise les anciennes valeurs éventuelles.
update public.acces_magasin set role = 'employe' where role is null or role not in ('admin','employe');

-- Le premier compte créé pour chaque magasin devient administrateur.
-- Pour un magasin déjà utilisé sur un seul téléphone, ce téléphone devient donc administrateur.
with premiers as (
  select distinct on (a.magasin_id) a.magasin_id, a.user_id
  from public.acces_magasin a
  left join auth.users u on u.id = a.user_id
  order by a.magasin_id, u.created_at asc nulls last, a.user_id
)
update public.acces_magasin a
set role = 'admin', actif = true, updated_at = now()
from premiers p
where a.magasin_id = p.magasin_id and a.user_id = p.user_id;

create table if not exists public.rayons (
  id bigint generated by default as identity primary key,
  magasin_id bigint not null references public.magasins(id) on delete cascade,
  nom text not null,
  position integer not null default 0,
  actif boolean not null default true,
  created_at timestamptz not null default now(),
  unique (magasin_id, nom)
);

insert into public.rayons (magasin_id, nom, position)
select m.id, r.nom, r.position
from public.magasins m
cross join (values
  ('Crèmerie',1),('Charcuterie',2),('Frais',3),('Traiteur',4),
  ('Épicerie',5),('Boucherie',6),('Poissonnerie',7)
) as r(nom,position)
on conflict (magasin_id, nom) do nothing;

alter table public.acces_magasin enable row level security;
alter table public.produits enable row level security;
alter table public.catalogue_produits enable row level security;
alter table public.rayons enable row level security;

grant select, insert, update, delete on public.acces_magasin to authenticated;
grant select, insert, update, delete on public.produits to authenticated;
grant select, insert, update, delete on public.catalogue_produits to authenticated;
grant select, insert, update, delete on public.rayons to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Fonctions de contrôle d'accès. SECURITY DEFINER évite la récursion des policies.
create or replace function public.est_membre_magasin(p_magasin_id bigint)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.acces_magasin a
    where a.user_id = auth.uid() and a.magasin_id = p_magasin_id and a.actif = true
  );
$$;

create or replace function public.est_admin_magasin(p_magasin_id bigint)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.acces_magasin a
    where a.user_id = auth.uid() and a.magasin_id = p_magasin_id
      and a.actif = true and a.role = 'admin'
  );
$$;

grant execute on function public.est_membre_magasin(bigint) to authenticated;
grant execute on function public.est_admin_magasin(bigint) to authenticated;

-- Supprime les anciennes policies de ces tables afin d'éviter qu'une ancienne règle plus permissive reste active.
do $$
declare p record;
begin
  for p in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname='public' and tablename in ('acces_magasin','produits','catalogue_produits','rayons')
  loop
    execute format('drop policy if exists %I on %I.%I', p.policyname, p.schemaname, p.tablename);
  end loop;
end $$;

-- Accès équipe : chacun voit son propre accès ; un admin voit et gère l'équipe du magasin.
create policy "acces lecture soi ou admin" on public.acces_magasin
for select to authenticated
using (user_id = auth.uid() or public.est_admin_magasin(magasin_id));

create policy "acces modification admin" on public.acces_magasin
for update to authenticated
using (public.est_admin_magasin(magasin_id))
with check (public.est_admin_magasin(magasin_id));

-- Produits DLC : tous les membres actifs du magasin peuvent travailler dessus.
create policy "produits lecture membre" on public.produits
for select to authenticated using (public.est_membre_magasin(magasin_id));
create policy "produits ajout membre" on public.produits
for insert to authenticated with check (public.est_membre_magasin(magasin_id));
create policy "produits modif membre" on public.produits
for update to authenticated using (public.est_membre_magasin(magasin_id)) with check (public.est_membre_magasin(magasin_id));
create policy "produits suppression membre" on public.produits
for delete to authenticated using (public.est_membre_magasin(magasin_id));

-- Catalogue : tout membre peut le lire et mémoriser un nouvel EAN ; seul l'admin peut corriger/supprimer.
create policy "catalogue lecture membre" on public.catalogue_produits
for select to authenticated using (public.est_membre_magasin(magasin_id));
create policy "catalogue ajout membre" on public.catalogue_produits
for insert to authenticated with check (public.est_membre_magasin(magasin_id));
create policy "catalogue modif admin" on public.catalogue_produits
for update to authenticated using (public.est_admin_magasin(magasin_id)) with check (public.est_admin_magasin(magasin_id));
create policy "catalogue suppression admin" on public.catalogue_produits
for delete to authenticated using (public.est_admin_magasin(magasin_id));

-- Rayons : visibles par toute l'équipe, modifiables uniquement par l'admin.
create policy "rayons lecture membre" on public.rayons
for select to authenticated using (public.est_membre_magasin(magasin_id));
create policy "rayons ajout admin" on public.rayons
for insert to authenticated with check (public.est_admin_magasin(magasin_id));
create policy "rayons modif admin" on public.rayons
for update to authenticated using (public.est_admin_magasin(magasin_id)) with check (public.est_admin_magasin(magasin_id));
create policy "rayons suppression admin" on public.rayons
for delete to authenticated using (public.est_admin_magasin(magasin_id));
